/* * Auto-generated by ec (embedded-C). Do not edit. * */
#ifndef ____TYPES_H__
#define ____TYPES_H__

#include <_stddef.h>

/**
 * @brief block count.
 */
typedef signed long __blkcnt_t;

/**
 * @brief block size.
 */
typedef signed long __blksize_t;

/**
 * @brief special character.
 */
typedef unsigned char __cc_t;

/**
 * @brief clock ticks.
 */
typedef signed long __clock_t;

/**
 * @brief device id.
 */
typedef unsigned long long __dev_t;

/**
 * @brief file system block count.
 */
typedef unsigned long __fsblkcnt_t;

/**
 * @brief file system file count.
 */
typedef unsigned long __fsfilcnt_t;

/**
 * @brief group id.
 */
typedef unsigned int __gid_t;

/**
 * @brief id.
 */
typedef unsigned int __id_t;

/**
 * @brief inode number.
 */
typedef unsigned long __ino_t;

/**
 * @brief exact 16bit signed integer.
 */
typedef signed short __int16_t;

/**
 * @brief exact 32bit signed integer.
 */
typedef signed int __int32_t;

/**
 * @brief exact 64bit signed integer.
 */
typedef signed long long __int64_t;

/**
 * @brief exact 8bit signed integer.
 */
typedef signed char __int8_t;

/**
 * @brief greatest signed integer type.
 */
typedef signed long long __intmax_t;

/**
 * @brief signed integer type enough to hold pointer to void.
 */
typedef signed int __intptr_t;

/**
 * @brief file mode.
 */
typedef unsigned int __mode_t;

/**
 * @brief link count
 */
typedef unsigned int __nlink_t;

/**
 * @brief file offset.
 */
typedef signed long __off_t;

/**
 * @brief process id.
 */
typedef signed int __pid_t;

/**
 * @brief difference of two pointers.
 */
typedef signed int __ptrdiff_t;

/**
 * @brief resource limit value.
 */
typedef unsigned long __rlim_t;

/**
 * @brief socket address family.
 */
typedef unsigned short __sa_family_t;

/**
 * @brief size of objects.
 */
typedef unsigned int __size_t;

/**
 * @brief length of sockaddr.
 */
typedef unsigned int __socklen_t;

/**
 * @brief terminal baud rate.
 */
typedef unsigned int __speed_t;

/**
 * @brief size of objects and error indication.
 */
typedef signed int __ssize_t;

/**
 * @brief time in microseconds.
 */
typedef signed long __suseconds_t;

/**
 * @brief terminal mode.
 */
typedef unsigned int __tcflag_t;

/**
 * @brief time in seconds.
 */
typedef signed long __time_t;

/**
 * @brief user id.
 */
typedef unsigned int __uid_t;

/**
 * @brief exact 16bit unsigned integer.
 */
typedef unsigned short __uint16_t;

/**
 * @brief exact 32bit unsigned integer.
 */
typedef unsigned int __uint32_t;

/**
 * @brief exact 64bit unsigned integer.
 */
typedef unsigned long long __uint64_t;

/**
 * @brief exact 8bit unsigned integer.
 */
typedef unsigned char __uint8_t;

/**
 * @brief greatest unsigned integer type.
 */
typedef unsigned long long __uintmax_t;

/**
 * @brief unsigned integer type enough to hold pointer to void.
 */
typedef unsigned int __uintptr_t;

/**
 * @brief time in microseconds.
 */
typedef unsigned int __useconds_t;

#endif
