/* Generated file -- do not edit. */
/* * Auto-generated by ec (embedded-C). Do not edit. * */
/**
 * @file include/signal.h
 */
#ifndef __SIGNAL_H
#define __SIGNAL_H

#include <sys/__types.h>
#include <time.h>

#ifndef __PID_T
#define __PID_T
typedef __pid_t pid_t;
#endif

#define SIG_DFL  ((void(*)(int))0)
#define SIG_ERR  ((void(*)(int))-1)
#define SIG_HOLD ((void(*)(int))2)
#define SIG_IGN  ((void(*)(int))1)

#define _NSIG 65

#define  SIGHUP    1
#define  SIGINT    2
#define  SIGQUIT   3
#define  SIGILL    4
#define  SIGTRAP   5
#define  SIGABRT   6
#define  SIGIOT    6
#define  SIGFPE    8
#define  SIGKILL   9
#define  SIGBUS    7
#define  SIGSEGV   11
#define  SIGSYS    31
#define  SIGPIPE   13
#define  SIGALRM   14
#define  SIGTERM   15
#define  SIGUSR1   10
#define  SIGUSR2   12
#define  SIGCHLD   17
#define  SIGPWR    30
#define  SIGWINCH  28
#define  SIGURG    23
#define  SIGPOLL   29
#define  SIGSTOP   19
#define  SIGTSTP   20
#define  SIGCONT   18
#define  SIGTTIN   21
#define  SIGTTOU   22
#define  SIGVTALRM 26
#define  SIGPROF   27
#define  SIGXCPU   24
#define  SIGXFSZ   25

#define SA_NOCLDSTOP 1

#define SIG_BLOCK     0
#define SIG_UNBLOCK   1
#define SIG_SETMASK   2

#define SA_ONSTACK   0x8000000
#define SA_RESETHAND 0x80000000
#define SA_RESTART   0x10000000
#define SA_SIGINFO   0x4
#define SA_NOCLDWAIT 0x2
#define SA_NODEFER   0x40000000

#define SS_ONSTACK   0x1
#define SS_DISABLE   0x2

#define SA_ONESHOT   0x80000000

/* TODO */
typedef int sig_atomic_t;

typedef struct __fsc_attribute__((named "stdlib_sigset_t")) __sigset_t {
  char v[65];
} sigset_t;

typedef struct __fsc_attribute__((named "stdlib_siginfo_t")) __siginfo_t {
  int si_signo;
  int si_errno;
  int si_code;
} siginfo_t;

struct __fsc_attribute__((named "stdlib_sigaction")) sigaction {
  void (*sa_handler)(int);
  void (*sa_sigaction)(int, siginfo_t *, void *);
  int sa_flags;
  sigset_t sa_mask;
};

extern int sigaction(int, const struct sigaction *, struct sigaction *);

extern void (*signal(int, void (*)(int)))(int);

extern int sigprocmask(int, const sigset_t *, sigset_t *);

extern int sigemptyset(sigset_t *);
extern int sigfillset(sigset_t *);
extern int sigaddset(sigset_t *, int);
extern int sigdelset(sigset_t *, int);
extern int sigismember(sigset_t *, int);

extern int raise(int);
extern int kill(pid_t, int);

extern int killpg(pid_t pgrp, int sig);
extern int sighold(int sig);
extern int sigignore(int sig);
extern int sigpause(int sig);
extern int sigrelse(int sig);

extern int siginterrupt(int sig, int flag);

extern int sigsuspend(const sigset_t *sigmask);
extern int sigpending(sigset_t *set);
extern int sigwait(const sigset_t *set, int *sig);

extern void (*sigset(int, void(*)(int)))(int);

#endif
